use clap::Parser;
use std::{
    collections::BTreeMap,
    path::{Component, Path, PathBuf},
};

/// All `.proto` files to compile, relative to the workspace root.
const PROTO_FILES: &[&str] = &[
    "packages/rust-ipns/src/generate/ipns_pb.proto",
    "src/p2p/bitswap/pb/bitswap_pb.proto",
];

#[derive(Debug, Parser)]
struct Opt {
    #[arg(long)]
    root: Option<PathBuf>,

    #[arg(long, value_name = "PROTO", num_args = 1..)]
    proto_files: Vec<PathBuf>,

    #[arg(long)]
    enable_bytes: Vec<String>,
}

fn main() {
    let Opt {
        root,
        proto_files,
        enable_bytes,
    } = Opt::parse();

    let root = root.unwrap_or_else(|| {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .expect("gen-proto must live two directories below the workspace root")
            .to_path_buf()
    });

    assert!(
        root.join("Cargo.toml").exists(),
        "workspace root not found at {}",
        root.display(),
    );

    let proto_files = if proto_files.is_empty() {
        PROTO_FILES
            .iter()
            .map(|path| PathBuf::from(*path))
            .collect()
    } else {
        proto_files
    };

    // Group proto files by parent directory (= include dir = output dir).
    let mut by_dir: BTreeMap<PathBuf, Vec<PathBuf>> = BTreeMap::new();

    for proto in proto_files {
        assert!(
            !proto.is_absolute()
                && !proto
                    .components()
                    .any(|component| matches!(component, Component::ParentDir)),
            "proto path must be relative to and contained within the workspace root: {}",
            proto.display(),
        );

        let dir = proto
            .parent()
            .filter(|path| !path.as_os_str().is_empty())
            .unwrap_or_else(|| Path::new("."))
            .to_path_buf();
        by_dir.entry(dir).or_default().push(proto);
    }

    // Compile each group with prost-build.
    for (dir, protos) in &by_dir {
        let abs_dir = root.join(dir);
        let abs_protos: Vec<PathBuf> = protos.iter().map(|p| root.join(p)).collect();

        println!("  {} file(s) in {}", protos.len(), dir.display());

        let proto_paths = abs_protos.iter().map(PathBuf::as_path).collect::<Vec<_>>();
        let file_descriptors = protox::compile(&proto_paths, [abs_dir.as_path()]).unwrap();

        let mut config = prost_build::Config::new();

        if !enable_bytes.is_empty() {
            config.bytes(enable_bytes.iter());
        }

        config
            .out_dir(&abs_dir)
            .compile_fds(file_descriptors)
            .unwrap_or_else(|e| panic!("failed to compile protos in {}: {e}", dir.display()));
    }

    // Generate a `mod.rs` in every output directory.
    for dir in by_dir.keys() {
        write_mod_rs(&root.join(dir));
    }

    println!("Done.");
}

/// Write a `mod.rs` that re-exports every generated `.rs` file in `dir`.
///
/// Files whose stem contains dots (e.g. `gossipsub.pb.rs`) get a `#[path]`
/// attribute because dots are not valid in Rust identifiers.
fn write_mod_rs(dir: &std::path::Path) {
    let mut files: Vec<String> = std::fs::read_dir(dir)
        .unwrap()
        .filter_map(|entry| {
            let name = entry.ok()?.file_name().into_string().ok()?;
            (name.ends_with(".rs") && name != "mod.rs").then_some(name)
        })
        .collect();
    files.sort();

    let mut out = String::from("// Automatically generated by gen-proto. DO NOT EDIT.\n");

    for file in &files {
        let stem = file.strip_suffix(".rs").unwrap();
        if stem.contains('.') {
            let mod_name = stem.replace('.', "_");
            out.push_str(&format!("#[path = \"{file}\"]\npub mod {mod_name};\n"));
        } else {
            out.push_str(&format!("pub mod {stem};\n"));
        }
    }

    std::fs::write(dir.join("mod.rs"), &out).unwrap();
}
